version: 2.0

jobs:
  cogutil:
    docker:
      - image: opencog/opencog-deps
        user: root
        # environment:
        #  CCACHE_DIR: /ws/ccache
    working_directory: /ws/cogutil
    steps:
      # - checkout
      - run:
          name: Checkout CogUtil branch
          command: cd /ws && git clone --single-branch --branch merge-from-opencog-to-singnet https://github.com/stellarspot/cogutil.git
      - run:
          name: Check current branch
          command: pwd && git branch
      #- run:
      #    name: Start restoring ccache
      #    command: date +%d-%m-%Y > /tmp/date
      #- restore_cache:
      #    keys:
      #      - ccache-{{ checksum "/tmp/date" }}
      #      - ccache-
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - run:
          name: Build
          command: cd build && make -j4
      - run:
          name: Build tests
          command: cd build && make -j4 tests
      - run:
          name: Run tests
          command:  cd build && make -j4 test
      - run:
          name: Print test log
          command: cat build/tests/Testing/Temporary/LastTest.log
          when: always
      - persist_to_workspace:
          root: /ws/
          paths:
            - cogutil
            #- ccache

  atomspace:
    docker:
      - image: opencog/opencog-deps
        user: root
        environment:
          PGHOST: opencog-postgres
          PGUSER: opencog_test
          PGPASSWORD: cheese
          #CCACHE_DIR: /ws/ccache
      - image: opencog/postgres
        name: opencog-postgres
    working_directory: /ws/atomspace
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install cogutil
          command: cd /ws/cogutil/build && make -j4 install && ldconfig
      - run:
          name: Clone AtomSpace
          # command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/atomspace .
          command: cd /ws && git clone --single-branch --branch merge-second-way-opencog-to-singnet-fix-tests https://github.com/stellarspot/atomspace.git
      - run:
          name: Check current branch
          command: pwd && git branch
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - run:
          name: Build
          command: cd build && make -j4
      - run:
          name: Install AtomSpace
          command: cd build && make -j4 install && ldconfig
      - run:
          name: Build tests
          command: cd build && make -j4 tests
      - run:
          name: Run tests
          #command: cd build && make -j4 test
          command: cd build && ulimit -c unlimited && make -j4 test
          #command: cd build && ulimit -c unlimited && ARGS='-R UREConfigUTest' make -j4 test
      - run:
          name: Copy core dumps
          command: |
            mkdir -p /tmp/core_dumps
            find build -name core.*
            find build -name core.* | xargs cp -t /tmp/core_dumps
            cp /lib/x86_64-linux-gnu/libc.so.6 /tmp/core_dumps
            cp /ws/atomspace/build/opencog/ure/libure.so /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - run:
          name: Print test log
          command: cat build/tests/Testing/Temporary/LastTest.log
          when: always
      - persist_to_workspace:
          root: /ws/
          paths:
            - atomspace
      #      - ccache

  moses:
    docker:
      - image: opencog/opencog-deps
        user: root
        #environment:
        #  CCACHE_DIR: /ws/ccache
    working_directory: /ws/moses
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install cogutil
          command: cd /ws/cogutil/build && make -j4 install && ldconfig
      - run:
          name: Clone MOSES
          command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/moses .
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j4
      - run:
          name: Build tests
          command: cd build && make -j4 tests
      - run:
          name: Run tests
          command: cd build && make -j4 test
      - run:
          name: Print test log
          command: cat build/tests/Testing/Temporary/LastTest.log
          when: always

  as-moses:
    docker:
      - image: opencog/opencog-deps
        user: root
        #environment:
        #  CCACHE_DIR: /ws/ccache
    working_directory: /ws/as-moses
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install cogutil
          command: cd /ws/cogutil/build && make -j4 install && ldconfig
      - run:
          name: Install AtomSpace
          command: cd /ws/atomspace/build && make -j4 install && ldconfig
      - run:
          name: Clone AS-MOSES
          command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/as-moses .
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j4
      - run:
          name: Build tests
          command: cd build && make -j4 tests
      - run:
          name: Run tests
          command: cd build && make -j4 test
      - run:
          name: Print test log
          command: cat build/tests/Testing/Temporary/LastTest.log
          when: always

  opencog:
    docker:
      - image: opencog/opencog-deps
        user: root
        #environment:
        #  CCACHE_DIR: /ws/ccache
    working_directory: /ws/opencog
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install cogutil
          command: cd /ws/cogutil/build && make -j4 install && ldconfig
      - run:
          name: Install AtomSpace
          command: cd /ws/atomspace/build && make -j4 install && ldconfig
      - run:
          name: Clone OpenCog
          #command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/opencog .
          command: cd /ws && git clone --single-branch --branch merge-opencog-to-singnet https://github.com/stellarspot/opencog.git
      - run:
          name: Check current branch
          command: pwd && git branch
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j4
      - run:
          name: Install OpenCog
          command: cd build && make -j4 install && ldconfig
      - run:
          name: Build tests
          command: cd build && make -j4 tests
      - run:
          name: Run tests
          command: cd build && make -j4 test
      - run:
          name: Print test log
          command: cat build/tests/Testing/Temporary/LastTest.log
          when: always
      #- persist_to_workspace:
      #    root: /ws/
      #    paths:
      #      - ccache

  package:
    docker:
      - image: opencog/opencog-deps
        user: root
    working_directory: /ws/cogutil
    steps:
      - attach_workspace:
          at: /ws/
      - run:
          name: Build Debian package
          command: cd build && make install && make package
      - store_artifacts:
          path: build/packages/
      #- run:
      #    name: Start storing ccache
      #    command: date +%d-%m-%Y > /tmp/date
      #- save_cache:
      #    key: ccache-{{ checksum "/tmp/date" }}
      #    paths:
      #      - /ws/ccache

workflows:
  version: 2
  build-test-package:
    jobs:
      - cogutil
      - atomspace:
          requires:
            - cogutil
      #- moses:
      #    requires:
      #      - cogutil
      #- as-moses:
      #    requires:
      #      - cogutil
      #      - atomspace
      - opencog:
          requires:
            - atomspace
      - package:
          requires:
            - opencog
          filters:
            branches:
              only: master
